config {
  type: "view",
  schema: dataform.projectConfig.vars.silver_dataset,
  description: "Campus Ministry analysis focusing on students, their schools, and courses.",
  tags: ["analytical"]
}

SELECT
  email,
  first_name,
  last_name,
  school,
  course,
  year_level,
  -- Helper for filtering by campus
  LOWER(school) AS school_normalized
FROM
  ${ref("members")}
WHERE
  occupation_type = 'Student'
